/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface PtcLogo {}
  interface PtcLogoAttributes extends StencilHTMLAttributes {}

  interface PtcHome {}
  interface PtcHomeAttributes extends StencilHTMLAttributes {}

  interface PtcProfile {
    'match': MatchResults;
  }
  interface PtcProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface PtcRoot {}
  interface PtcRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PtcLogo': Components.PtcLogo;
    'PtcHome': Components.PtcHome;
    'PtcProfile': Components.PtcProfile;
    'PtcRoot': Components.PtcRoot;
  }

  interface StencilIntrinsicElements {
    'ptc-logo': Components.PtcLogoAttributes;
    'ptc-home': Components.PtcHomeAttributes;
    'ptc-profile': Components.PtcProfileAttributes;
    'ptc-root': Components.PtcRootAttributes;
  }


  interface HTMLPtcLogoElement extends Components.PtcLogo, HTMLStencilElement {}
  var HTMLPtcLogoElement: {
    prototype: HTMLPtcLogoElement;
    new (): HTMLPtcLogoElement;
  };

  interface HTMLPtcHomeElement extends Components.PtcHome, HTMLStencilElement {}
  var HTMLPtcHomeElement: {
    prototype: HTMLPtcHomeElement;
    new (): HTMLPtcHomeElement;
  };

  interface HTMLPtcProfileElement extends Components.PtcProfile, HTMLStencilElement {}
  var HTMLPtcProfileElement: {
    prototype: HTMLPtcProfileElement;
    new (): HTMLPtcProfileElement;
  };

  interface HTMLPtcRootElement extends Components.PtcRoot, HTMLStencilElement {}
  var HTMLPtcRootElement: {
    prototype: HTMLPtcRootElement;
    new (): HTMLPtcRootElement;
  };

  interface HTMLElementTagNameMap {
    'ptc-logo': HTMLPtcLogoElement
    'ptc-home': HTMLPtcHomeElement
    'ptc-profile': HTMLPtcProfileElement
    'ptc-root': HTMLPtcRootElement
  }

  interface ElementTagNameMap {
    'ptc-logo': HTMLPtcLogoElement;
    'ptc-home': HTMLPtcHomeElement;
    'ptc-profile': HTMLPtcProfileElement;
    'ptc-root': HTMLPtcRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
